name: flutter_onboarding_ui
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family: CM Sans Serif
     fonts:
       - asset: assets/fonts/cm_sans_serif_2012.ttf

   - family: Sketch
     fonts:
       - asset: assets/fonts/CabinSketch-Regular.ttf

   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Light.ttf

   - family: Oswald
     fonts:
       - asset: assets/fonts/Oswald-VariableFont_wght.ttf


   - family: Risque
     fonts:
       - asset: assets/fonts/Risque-Regular.ttf



